<Workspace Version="1.3.0.875" X="-656.807377358445" Y="688.61424931133" zoom="0.694308384947013" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="9422f8ee-3f2b-402b-89ab-d1508f08b1c1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1401.25102295284" y="-596.982663133103" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
# need to learn how to implement LINQ here...
collector = FilteredElementCollector(doc)
impinst = collector.OfClass(ImportInstance).ToElements()
linkedlist = list()
importlist = list()
count = 0
for item in impinst:
	if item.IsLinked:
		linkedlist.append(item)
	else:
		importlist.append(item)
if IN[1]:
	TransactionManager.Instance.EnsureInTransaction(doc)
	for imp in importlist:
		doc.Delete(imp.Id)
		count = count+1
	TransactionManager.Instance.TransactionTaskDone()

OUT = "Удалённых элементов="+str(count)</Script>
    </PythonNodeModels.PythonNode>
    <Prorubim.DS.Common.ForceChildrensEval guid="45f4b2c2-e91b-48b1-ad72-b7cbf71c497f" type="Prorubim.DS.Common.ForceChildrensEval" nickname="ForceChildrensEval" x="1134.09839713707" y="-598.359738523906" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </Prorubim.DS.Common.ForceChildrensEval>
    <CoreNodeModels.Input.BoolSelector guid="5dea31eb-1c87-403f-ba59-623be51260bf" type="CoreNodeModels.Input.BoolSelector" nickname="Удалить?" x="1174.42433576199" y="-438.982797533856" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="45f4b2c2-e91b-48b1-ad72-b7cbf71c497f" start_index="0" end="9422f8ee-3f2b-402b-89ab-d1508f08b1c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5dea31eb-1c87-403f-ba59-623be51260bf" start_index="0" end="9422f8ee-3f2b-402b-89ab-d1508f08b1c1" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="81ae9242-de08-4c54-878d-8aaaef39e061" annotationText="" left="1124.09839713707" top="-644.359738523906" width="411.152625815771" height="166.377075390803" fontSize="30" InitialTop="-598.359738523906" InitialHeight="124.377075390803" TextblockHeight="36" backgrouund="#FF71C6A8">
      <Models ModelGuid="9422f8ee-3f2b-402b-89ab-d1508f08b1c1" />
      <Models ModelGuid="45f4b2c2-e91b-48b1-ad72-b7cbf71c497f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>