<Workspace Version="1.2.1.3083" X="-1122.94440173655" Y="-692.892654098919" zoom="0.706231785777504" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="da621fed-e311-49b4-b205-709d3c54945f" type="PythonNodeModels.PythonNode" nickname="PyS Get Revit Selection" x="1308.8494268304" y="1045.59457760335" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitServices')
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import RevitServices
from RevitServices.Persistence import DocumentManager
from Autodesk.Revit.ApplicationServices import Application

reset = IN[0]

doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
ids = uidoc.Selection.GetElementIds()

idd = [str(i) for i in ids]

if isinstance(idd, list) == True:
	elems = [doc.GetElement(ElementId(int(i))) for i in idd]
else:
	elems = doc.GetElement(ElementId(int(idd)))

OUT = elems
</Script>
    </PythonNodeModels.PythonNode>
    <Prorubim.DS.Common.ForceChildrensEval guid="3f8863ea-3c3e-4c9d-ab8a-5761d4d92294" type="Prorubim.DS.Common.ForceChildrensEval" nickname="ForceChildrensEval" x="1067.02950256315" y="1046.42816295334" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </Prorubim.DS.Common.ForceChildrensEval>
    <PythonNodeModels.PythonNode guid="bcef645b-114f-47f8-9a0d-d40aa7a6bd65" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2594.80044624792" y="1043.86694961901" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
walls = UnwrapElement(IN[0])
elementlist = list()

TransactionManager.Instance.EnsureInTransaction(doc)
for item in walls:
	try:
		item.Flip()
		elementlist.append(item)
	except:
		elementlist.append(list())
TransactionManager.Instance.TransactionTaskDone()
		
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="8ef93f5b-1203-4dc1-9a07-3cb44b94ce39" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="WallLocationLine.CoreCenterline" x="1642.11137997218" y="1657.81258684801" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <ID value="12fdf076-77a9-4aea-8fbf-80a584a5fbfa" />
      <Name value="WallLocationLine.CoreCenterline" />
      <Description value="Returns the WallLocationLine option for CoreCenterLine" />
      <Inputs />
      <Outputs>
        <Output value="CoreCenterline" />
        <Output value="int" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a75214ee-8a98-40ef-acea-f98e80c5592e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="2194.51437569657" y="1049.87661907965" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="2a6016b1-6242-4135-8f9c-3b6906397368" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="WallLocationLine.FinishFaceInterior" x="1632.21252264937" y="1434.58170720475" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <ID value="66a8de31-e6ac-4f05-9ead-93ac8372e358" />
      <Name value="WallLocationLine.FinishFaceInterior" />
      <Description value="Returns the WallLocationLine option for FinishFaceInterior" />
      <Inputs />
      <Outputs>
        <Output value="FinishFaceInterior" />
        <Output value="int" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="80297058-e1ce-4c2b-9165-e6d1888c5153" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="WallLocationLine.FinishFaceExterior" x="1630.6354939032" y="1218.88063920683" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <ID value="28126966-67ff-4b1f-ae5c-47993debcca6" />
      <Name value="WallLocationLine.FinishFaceExterior" />
      <Description value="Returns the WallLocationLine option for FinishFaceExterior" />
      <Inputs />
      <Outputs>
        <Output value="FinishFaceExterior" />
        <Output value="int" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c4a6f929-d42e-40f5-b39a-13ab5f9ca6a4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1900.16875053795" y="1128.64294057415" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Линия привязки&quot;;&#xA;1;&#xA;3;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e1dbfe4e-c761-4971-84d5-de610f24bbc9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="1899.67200444258" y="1657.91991561264" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2e760ac6-f54b-4787-8a5a-a5942d377d4d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="2908.63181787728" y="1105.2757621138" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="da621fed-e311-49b4-b205-709d3c54945f" start_index="0" end="a75214ee-8a98-40ef-acea-f98e80c5592e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3f8863ea-3c3e-4c9d-ab8a-5761d4d92294" start_index="0" end="da621fed-e311-49b4-b205-709d3c54945f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bcef645b-114f-47f8-9a0d-d40aa7a6bd65" start_index="0" end="2e760ac6-f54b-4787-8a5a-a5942d377d4d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a75214ee-8a98-40ef-acea-f98e80c5592e" start_index="0" end="bcef645b-114f-47f8-9a0d-d40aa7a6bd65" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4a6f929-d42e-40f5-b39a-13ab5f9ca6a4" start_index="0" end="a75214ee-8a98-40ef-acea-f98e80c5592e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4a6f929-d42e-40f5-b39a-13ab5f9ca6a4" start_index="0" end="2e760ac6-f54b-4787-8a5a-a5942d377d4d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4a6f929-d42e-40f5-b39a-13ab5f9ca6a4" start_index="1" end="a75214ee-8a98-40ef-acea-f98e80c5592e" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4a6f929-d42e-40f5-b39a-13ab5f9ca6a4" start_index="2" end="2e760ac6-f54b-4787-8a5a-a5942d377d4d" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="c677149c-1220-45e3-a651-860cb5479329" annotationText="Get Revit Selection:" left="1057.02950256315" top="1015.59457760335" width="407.81992426725" height="123.83358534999" fontSize="14" InitialTop="1045.59457760335" InitialHeight="207.623313027957" TextblockHeight="20" backgrouund="#FF71C6A8">
      <Models ModelGuid="da621fed-e311-49b4-b205-709d3c54945f" />
      <Models ModelGuid="3f8863ea-3c3e-4c9d-ab8a-5761d4d92294" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>