<Workspace Version="1.3.2.2480" X="-396.232253899342" Y="-368.173563724714" zoom="0.813921233607364" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c72124d5-4bf4-4a24-a5b8-bde4ae9261e8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1352.22958886446" y="614.687446973366" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
import System.Object
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

input = UnwrapElement(IN[0])
elt=[]
for i in input:
	elt.append(i.Id)

collection = List[ElementId](elt)

uidoc.Selection.SetElementIds(collection)

OUT = input,collection</Script>
    </PythonNodeModels.PythonNode>
    <Prorubim.DS.Common.ForceChildrensEval guid="43199a9d-1860-46a5-adc9-6a57f6615f74" type="Prorubim.DS.Common.ForceChildrensEval" nickname="ForceChildrensEval" x="-479.61808210569" y="695.321240166508" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </Prorubim.DS.Common.ForceChildrensEval>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0fb74942-a505-4f6d-ac6c-6e9e8a12c588" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-475.52456622774" y="608.476267500568" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="refresh:bool = true;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="b190125f-8b91-4633-a2fc-64fe2102ff5b" type="PythonNodeModels.PythonNode" nickname="выделение элементов активного вида" x="-226.368298511207" y="618.807349359215" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

#inspired by Troy Gates https://forums.autodesk.com/t5/revit-api/revit-api-selected-element-set-order/td-p/5597203

import clr

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def output1(l1):
	if len(l1) == 1: return l1[0]
	else: return l1

sel1 = uidoc.Selection
obt1 = Selection.ObjectType.Element
msg1 = 'Pick elements in the desired order, hit ESC to stop picking.'
out1 = []

flag = True
TaskDialog.Show("Spring Nodes", msg1)
while flag:
	try:
		el1 = doc.GetElement(sel1.PickObject(obt1, msg1).ElementId)
		out1.append(el1.ToDSType(True))
	except : flag = False

OUT = output1(out1)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="65425e2f-889c-4715-81bf-cac0fc04e914" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1139.8206675783" y="615.233417500559" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f634ed0b-91f8-4297-9d48-5fef8e32aa63" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.Type" x="70.4179962447316" y="615.456388827102" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="4796d57c-a1a0-4676-b524-57abb5fa73be" />
      <Name value="Element.Type" />
      <Description value="Gets the family type of a given element (if applicable). " />
      <Inputs>
        <Input value="element" />
      </Inputs>
      <Outputs>
        <Output value="type" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <DSRevitNodesUI.ElementsOfFamilyType guid="26d8c1f2-e22a-445a-8e1d-1ab40361d56e" type="DSRevitNodesUI.ElementsOfFamilyType" nickname="All Elements of Family Type" x="284.929431362069" y="617.866684949053" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfFamilyType>
    <DSRevitNodesUI.ElementsInView guid="82e5877e-cc2b-48df-b3ab-3c032883ee97" type="DSRevitNodesUI.ElementsInView" nickname="All Elements In Active View" x="295.194086932898" y="532.036554973345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d4cfa40c-dc3e-45d3-8e0a-54b6cdb8729a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="941.795339679713" y="610.677409643882" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6dd973ed-bd00-45be-9f72-429a3f6c352c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.ContainsItem" x="727.329194993427" y="523.077699988553" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.ContainsItem@var[]..[],var">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7dc7ede9-5841-46d6-84d8-782d970aaaa3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="512.480842596393" y="620.257450587916" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="43199a9d-1860-46a5-adc9-6a57f6615f74" start_index="0" end="b190125f-8b91-4633-a2fc-64fe2102ff5b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0fb74942-a505-4f6d-ac6c-6e9e8a12c588" start_index="0" end="b190125f-8b91-4633-a2fc-64fe2102ff5b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b190125f-8b91-4633-a2fc-64fe2102ff5b" start_index="0" end="f634ed0b-91f8-4297-9d48-5fef8e32aa63" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="65425e2f-889c-4715-81bf-cac0fc04e914" start_index="0" end="c72124d5-4bf4-4a24-a5b8-bde4ae9261e8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f634ed0b-91f8-4297-9d48-5fef8e32aa63" start_index="0" end="26d8c1f2-e22a-445a-8e1d-1ab40361d56e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="26d8c1f2-e22a-445a-8e1d-1ab40361d56e" start_index="0" end="7dc7ede9-5841-46d6-84d8-782d970aaaa3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82e5877e-cc2b-48df-b3ab-3c032883ee97" start_index="0" end="6dd973ed-bd00-45be-9f72-429a3f6c352c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d4cfa40c-dc3e-45d3-8e0a-54b6cdb8729a" start_index="0" end="65425e2f-889c-4715-81bf-cac0fc04e914" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6dd973ed-bd00-45be-9f72-429a3f6c352c" start_index="0" end="d4cfa40c-dc3e-45d3-8e0a-54b6cdb8729a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7dc7ede9-5841-46d6-84d8-782d970aaaa3" start_index="0" end="6dd973ed-bd00-45be-9f72-429a3f6c352c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7dc7ede9-5841-46d6-84d8-782d970aaaa3" start_index="0" end="d4cfa40c-dc3e-45d3-8e0a-54b6cdb8729a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="e2ddad3d-ccd0-43d7-874a-d50bca7e9831" annotationText="Выделение элементов" left="1342.22958886446" top="532.687446973366" width="162.506666666667" height="175" fontSize="30" InitialTop="614.687446973366" InitialHeight="124.221894351286" TextblockHeight="72" backgrouund="#FF71C6A8">
      <Models ModelGuid="c72124d5-4bf4-4a24-a5b8-bde4ae9261e8" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>