<Workspace Version="1.3.0.875" X="-961.577117970169" Y="223.396653139673" zoom="0.74841074609604" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.BoolSelector guid="048dd4bf-99e8-4e36-8609-642692eccee7" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="-90.8068374676338" y="-33.3433033201284" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <CoreNodeModels.Input.StringInput guid="6194e2c3-d50a-4c2a-8998-4f6e8a5474c6" type="CoreNodeModels.Input.StringInput" nickname="String" x="1263.03679111632" y="125.38474451861" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>Номер цепи</System.String>
      <System.String value="Номер цепи" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="8ad96359-a6c2-44c1-9cbe-71c5345e8111" type="CoreNodeModels.Input.StringInput" nickname="String" x="1385.43554868995" y="-122.590694201354" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>Марка</System.String>
      <System.String value="Марка" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="1ad34170-b7a9-4ff2-a5f6-d8bbc95d4637" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Springs.Collector.CurrentSelection" x="382.754909834025" y="-23.4405790666474" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="True" />
      <ID value="f153d48d-85dd-4a7e-8ba2-91b08d81e5e7" />
      <Name value="Springs.Collector.CurrentSelection" />
      <Description value="Gets the currently selected elements. Connect a boolean switch to refresh the selection." />
      <Inputs>
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="element(s)" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Prorubim.DS.Common.ForceChildrensEval guid="caf3c2c7-33cc-4bb7-9dae-5e1cc18481cf" type="Prorubim.DS.Common.ForceChildrensEval" nickname="ForceChildrensEval" x="146.004181936476" y="-23.8738915198863" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </Prorubim.DS.Common.ForceChildrensEval>
    <PythonNodeModels.PythonNode guid="25c16d96-65a2-421f-a845-1a61ed2e8dc8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1498.65048354251" y="119.548403880677" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

dataEnteringNode = IN

list = dataEnteringNode[0]
pname = dataEnteringNode[1]

outlist = []

for e in list:
	try:
		outlist.append(e.GetParameterValueByName(pname))
	except:
		outlist.append(0)
		
	
		
		
		
	

OUT = outlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="6c00aae7-a0d5-44e2-95b7-23853034fbbc" type="PythonNodeModels.PythonNode" nickname="Element.ElectricalCircuit" x="1200.91585510251" y="-8.06653607126782" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The inputs to this node will be stored as a list in the IN variables.
if isinstance(IN[0],list):
	toggle = 0
	element = UnwrapElement(IN[0])
else:
	toggle = 1
	element = [UnwrapElement(IN[0])]

def getSystem(elem):
	system = elem.MEPModel.ElectricalSystems
	
	if system.Size == 0:
		return None
	elif system.Size == 1:	
		for sys in system:
			return sys
	else:
		return [x for x in system]

listout = []	
for x in element:
	try:
		system = getSystem(x)
		listout.append(system)
	except:
		listout.append(None)
#Assign your output to the OUT variable.
if toggle:
	OUT = system
else:
	OUT = listout</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="ceaecae1-3d04-4fec-95ab-d903028c790b" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Springs.Doc.ActiveView" x="127.95006455644" y="-256.163994657938" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="True" />
      <ID value="58849545-7510-4baf-99da-98c0b1e184fd" />
      <Name value="Springs.Doc.ActiveView" />
      <Description value="Selects the current document's active view. Supports more view types than the built-in option.&#xD;&#xA;Will be depreciated once the bult in node works with all plan types." />
      <Inputs>
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="view" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="738399d4-95df-4f7f-b25a-e590d427d255" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Select.ByCategoryAndView" x="381.199857482406" y="-385.071943585301" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="C:\Users\nabiev\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\archi-lab.net\bin\Archi-lab_Grimshaw.dll" function="Archilab.Grimshaw.Selection.Select.ByCategoryAndView@Revit.Elements.Category,Revit.Elements.Views.View">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Categories guid="19b3a5fa-c04c-418f-add9-69a4b785ec41" type="DSRevitNodesUI.Categories" nickname="Categories" x="54.5846540133419" y="-423.560342705879" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="583:ElectricalEquipment" />
    <CoreNodeModels.Watch guid="cabfbcf6-af1d-44f4-9bf0-64ab1bb40247" type="CoreNodeModels.Watch" nickname="Watch" x="807.509496408977" y="-194.037525069619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="df953460-9042-4306-9495-980c6de164da" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1721.32492103777" y="-253.149238002898" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

dataEnteringNode = IN

elements = dataEnteringNode[0]
pname = dataEnteringNode[1]
circuitnumbers = dataEnteringNode[2]


outlist = []
k =0 

for e in elements:
	try:
		e.SetParameterByName(pname, circuitnumbers[k].ToString())
		outlist.append(e.GetParameterValueByName(pname))
	except:	
		outlist.append(e.GetParameterValueByName(pname))
	k=k+1
		
	
		
		
		
	

OUT = outlist</Script>
    </PythonNodeModels.PythonNode>
    <Prorubim.DS.Common.ForceChildrensEval guid="742c4e91-4986-4122-a9bb-d4761c04ce7b" type="Prorubim.DS.Common.ForceChildrensEval" nickname="ForceChildrensEval" x="619.509179691801" y="-371.050385232733" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </Prorubim.DS.Common.ForceChildrensEval>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="048dd4bf-99e8-4e36-8609-642692eccee7" start_index="0" end="caf3c2c7-33cc-4bb7-9dae-5e1cc18481cf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="048dd4bf-99e8-4e36-8609-642692eccee7" start_index="0" end="ceaecae1-3d04-4fec-95ab-d903028c790b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6194e2c3-d50a-4c2a-8998-4f6e8a5474c6" start_index="0" end="25c16d96-65a2-421f-a845-1a61ed2e8dc8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ad96359-a6c2-44c1-9cbe-71c5345e8111" start_index="0" end="df953460-9042-4306-9495-980c6de164da" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="caf3c2c7-33cc-4bb7-9dae-5e1cc18481cf" start_index="0" end="1ad34170-b7a9-4ff2-a5f6-d8bbc95d4637" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="25c16d96-65a2-421f-a845-1a61ed2e8dc8" start_index="0" end="df953460-9042-4306-9495-980c6de164da" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c00aae7-a0d5-44e2-95b7-23853034fbbc" start_index="0" end="25c16d96-65a2-421f-a845-1a61ed2e8dc8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ceaecae1-3d04-4fec-95ab-d903028c790b" start_index="0" end="738399d4-95df-4f7f-b25a-e590d427d255" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="738399d4-95df-4f7f-b25a-e590d427d255" start_index="0" end="742c4e91-4986-4122-a9bb-d4761c04ce7b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="19b3a5fa-c04c-418f-add9-69a4b785ec41" start_index="0" end="738399d4-95df-4f7f-b25a-e590d427d255" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cabfbcf6-af1d-44f4-9bf0-64ab1bb40247" start_index="0" end="6c00aae7-a0d5-44e2-95b7-23853034fbbc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cabfbcf6-af1d-44f4-9bf0-64ab1bb40247" start_index="0" end="df953460-9042-4306-9495-980c6de164da" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="742c4e91-4986-4122-a9bb-d4761c04ce7b" start_index="0" end="cabfbcf6-af1d-44f4-9bf0-64ab1bb40247" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>