<Workspace Version="1.2.1.3083" X="-713.411093275973" Y="-531.379200109216" zoom="0.758687192219647" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Prorubim.DS.Common.ForceChildrensEval guid="b3769843-9cc9-43b9-b392-68cee1ab9936" type="Prorubim.DS.Common.ForceChildrensEval" nickname="ForceChildrensEval" x="775.608690182513" y="885.45774592402" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </Prorubim.DS.Common.ForceChildrensEval>
    <PythonNodeModels.PythonNode guid="264933ac-4b3a-4530-bea1-0b20fad90335" type="PythonNodeModels.PythonNode" nickname="PyS Get Revit Selection" x="1073.70760983507" y="1020.89496463153" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitServices')
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import RevitServices
from RevitServices.Persistence import DocumentManager
from Autodesk.Revit.ApplicationServices import Application

reset = IN[0]

doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
ids = uidoc.Selection.GetElementIds()

idd = [str(i) for i in ids]

if isinstance(idd, list) == True:
	elems = [doc.GetElement(ElementId(int(i))) for i in idd]
else:
	elems = doc.GetElement(ElementId(int(idd)))

OUT = elems
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="1095b0ae-73c3-48b2-98e5-739cab39dbbd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1614.71045433172" y="996.41610152779" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
doc = DocumentManager.Instance.CurrentDBDocument
from System.Collections.Generic import *
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

reset = IN[0]
grids = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)
view = doc.ActiveView
for grid in grids:
	grid.SetDatumExtentType(DatumEnds.End1,view,DatumExtentType.ViewSpecific)
	grid.SetDatumExtentType(DatumEnds.End0,view,DatumExtentType.ViewSpecific)
TransactionManager.Instance.TransactionTaskDone()

OUT = view</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b3769843-9cc9-43b9-b392-68cee1ab9936" start_index="0" end="264933ac-4b3a-4530-bea1-0b20fad90335" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b3769843-9cc9-43b9-b392-68cee1ab9936" start_index="0" end="1095b0ae-73c3-48b2-98e5-739cab39dbbd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="264933ac-4b3a-4530-bea1-0b20fad90335" start_index="0" end="1095b0ae-73c3-48b2-98e5-739cab39dbbd" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="7a603885-a7a9-4067-85a7-740ef304d74b" annotationText="Get Revit Selection:" left="765.608690182513" top="855.45774592402" width="464.098919652557" height="258.43721870751" fontSize="14" InitialTop="885.45774592402" InitialHeight="126.79024403617" TextblockHeight="20" backgrouund="#FF71C6A8">
      <Models ModelGuid="264933ac-4b3a-4530-bea1-0b20fad90335" />
      <Models ModelGuid="b3769843-9cc9-43b9-b392-68cee1ab9936" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-14.1199998855591" eyeY="20.8799991607666" eyeZ="36.0800018310547" lookX="9.11999988555908" lookY="-9.88000011444092" lookZ="-44.0800018310547" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>